{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aquafarm.fullname" . }}
  labels:
    {{- include "aquafarm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "aquafarm.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    - podSelector:
        matchLabels:
          {{- include "aquafarm.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
  egress:
  - {} # allow all egress
{{- end }}
