{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aquafarm.fullname" . }}-nginx
  labels:
    {{- include "aquafarm.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "aquafarm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}
