{{- if .Values.monitoring.tracing.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aquafarm.fullname" . }}-otel-config
  labels:
    {{- include "aquafarm.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_binary:
            endpoint: 0.0.0.0:6832
      zipkin:
        endpoint: 0.0.0.0:9411
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['0.0.0.0:8888']
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      memory_limiter:
        limit_mib: 512
        spike_limit_mib: 128
        check_interval: 5s
      resource:
        attributes:
          - key: service.name
            value: aquafarm
            action: upsert
          - key: service.version
            value: "0.2.0"
            action: upsert
    
    exporters:
      logging:
        loglevel: debug
      jaeger:
        endpoint: {{ .Values.monitoring.tracing.jaegerEndpoint | default "jaeger:14250" }}
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
    
    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger, zipkin]
          processors: [memory_limiter, batch, resource]
          exporters: [logging, jaeger]
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter, batch]
          exporters: [logging, prometheus]
{{- end }}
