{{- if .Values.externalDatabase.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aquafarm.fullname" . }}-database
  labels:
    {{- include "aquafarm.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.externalDatabase.url | b64enc }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aquafarm.fullname" . }}-database
  labels:
    {{- include "aquafarm.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "aquafarm.fullname" .) .Values.postgresql.auth.database | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aquafarm.fullname" . }}-redis
  labels:
    {{- include "aquafarm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.externalRedis.url }}
  url: {{ .Values.externalRedis.url | b64enc }}
  {{- else }}
  url: {{ printf "redis://%s:%s@%s-redis-master:6379" (ternary .Values.redis.auth.username "" .Values.redis.auth.enabled) (ternary .Values.redis.auth.password "" .Values.redis.auth.enabled) (include "aquafarm.fullname" .) | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aquafarm.fullname" . }}-jwt
  labels:
    {{- include "aquafarm.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.backend.env.JWT_SECRET | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aquafarm.fullname" . }}-object-storage
  labels:
    {{- include "aquafarm.labels" . | nindent 4 }}
type: Opaque
data:
  provider: {{ .Values.objectStorage.provider | b64enc }}
  endpoint: {{ .Values.objectStorage.endpoint | b64enc }}
  region: {{ .Values.objectStorage.region | b64enc }}
  bucket: {{ .Values.objectStorage.bucket | b64enc }}
  useSSL: {{ ternary "true" "false" .Values.objectStorage.useSSL | b64enc }}
  accessKey: {{ .Values.objectStorage.accessKey | b64enc }}
  secretKey: {{ .Values.objectStorage.secretKey | b64enc }}
