apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: aquafarm-prod
data:
  NEXT_PUBLIC_API_URL: "https://api.aquafarm-pro.com"
  NEXT_PUBLIC_APP_URL: "https://aquafarm-pro.com"
  NEXT_PUBLIC_WS_URL: "wss://api.aquafarm-pro.com"
  NODE_ENV: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: aquafarm-prod
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: aquafarm/frontend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-config
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: aquafarm-prod
  labels:
    app: frontend
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: frontend
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: aquafarm-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
