apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-secret
  namespace: aquafarm-prod
type: Opaque
data:
  pgbouncer-password: YXF1YWZhcm1fcGFzc3dvcmQ=  # aquafarm_password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: aquafarm-prod
data:
  pgbouncer.ini: |
    [databases]
    aquafarm = host=postgres port=5432 dbname=aquafarm user=aquafarm password=aquafarm_password
    
    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 25
    reserve_pool_size = 5
    reserve_pool_timeout = 3
    max_db_connections = 100
    max_user_connections = 50
    server_round_robin = 1
    ignore_startup_parameters = extra_float_digits
    application_name_add_host = 1
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    stats_period = 60
    verbose = 0
    admin_users = aquafarm
    stats_users = aquafarm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: aquafarm-prod
  labels:
    app: pgbouncer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
      - name: pgbouncer
        image: pgbouncer/pgbouncer:latest
        ports:
        - containerPort: 6432
        env:
        - name: PGBOUNCER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgbouncer-secret
              key: pgbouncer-password
        volumeMounts:
        - name: pgbouncer-config
          mountPath: /etc/pgbouncer
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          exec:
            command:
            - psql
            - -h
            - localhost
            - -p
            - "6432"
            - -U
            - aquafarm
            - -d
            - pgbouncer
            - -c
            - "SHOW VERSION;"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - psql
            - -h
            - localhost
            - -p
            - "6432"
            - -U
            - aquafarm
            - -d
            - pgbouncer
            - -c
            - "SHOW VERSION;"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: pgbouncer-config
        configMap:
          name: pgbouncer-config
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: aquafarm-prod
  labels:
    app: pgbouncer
spec:
  ports:
  - port: 6432
    targetPort: 6432
    name: pgbouncer
  selector:
    app: pgbouncer
  type: ClusterIP
