# =================================
# AquaFarm Pro - Prometheus Configuration
# =================================
# 
# تاريخ: 1 أكتوبر 2025
# تكوين Prometheus لمراقبة الأداء
# =================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aquafarm-production'
    replica: 'prometheus-1'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Backend API metrics
  - job_name: 'aquafarm-backend'
    static_configs:
      - targets: ['backend:3000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Frontend metrics (if available)
  - job_name: 'aquafarm-frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    scrape_timeout: 5s

  # Nginx metrics
  - job_name: 'aquafarm-nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    scrape_timeout: 5s

  # PostgreSQL metrics (if postgres_exporter is available)
  - job_name: 'aquafarm-postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    scrape_timeout: 5s

  # Redis metrics (if redis_exporter is available)
  - job_name: 'aquafarm-redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 5s

  # Node exporter for system metrics
  - job_name: 'aquafarm-node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 5s

  # Docker metrics
  - job_name: 'aquafarm-docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s
    scrape_timeout: 5s

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB

# Remote write configuration (optional)
# remote_write:
#   - url: "https://your-remote-storage.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"