## Backup of corrupted OpenAPI file (do not use in tooling)
## Timestamp: 2025-09-27
## Reason: YAML structural corruption (duplicate embedded document under responses/400 -> schema)

openapi_corrupted_snapshot: |
  (Original content preserved below exactly as captured prior to repair)
  ----------------------------------------------------------------------
  openapi: 3.1.0
  jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
  (truncated for brevity in backup – full nested duplication retained in git history if needed)