openapi: 3.0.3
info:
  title: AquaFarm Pro API
  version: 0.1.0
  description: Core endpoints for tenancy, IAM, farm, and accounting modules.
servers:
  - url: https://api.aquafarm.local/v1
    description: Staging
security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Tenant:
      type: object
      properties:
        id: { type: string, format: uuid }
        name: { type: string }
        locale: { type: string }
    User:
      type: object
      properties:
        id: { type: string, format: uuid }
        tenant_id: { type: string, format: uuid }
        email: { type: string, format: email }
        name: { type: string }
        locale: { type: string }
    Pond:
      type: object
      properties:
        id: { type: string, format: uuid }
        tenant_id: { type: string, format: uuid }
        code: { type: string }
        name: { type: string }

paths:
  /auth/login:
    post:
      summary: Login and get JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: JWT issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token: { type: string }
                  refresh_token: { type: string }
  /tenants:
    get:
      summary: List tenants (admin)
      responses: { '200': { description: OK } }
    post:
      summary: Create tenant
      responses: { '201': { description: Created } }
  /ponds:
    get:
      summary: List ponds
      responses: { '200': { description: OK } }
    post:
      summary: Create pond
      responses: { '201': { description: Created } }
  /journal-entries:
    post:
      summary: Create journal entry with lines
      responses: { '201': { description: Created } }