name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'

permissions:
  contents: read

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package.json
      - name: Install deps
        working-directory: backend
        run: npm ci
      - name: ESLint
        working-directory: backend
        run: npm run lint -- --max-warnings=0 || (echo "::warning::Lint warnings present" && exit 1)
      - name: Type Check (build dry run)
        working-directory: backend
        run: npm run build --silent

  test:
    name: Test (SQLite & Postgres)
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db: [sqlite, postgres]
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aquafarm
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=5s --health-timeout=5s --health-retries=5
    env:
      NODE_ENV: test
      SERVICE_NAME: aquafarm-backend
      DB_TYPE: ${{ matrix.db }}
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/aquafarm
      JWT_SECRET: testsecret
      DEFAULT_TENANT_ID: default-tenant
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package.json
      - name: Install deps
        working-directory: backend
        run: npm ci
      - name: Build
        working-directory: backend
        run: npm run build
      - name: Run E2E Tests
        working-directory: backend
        run: |
          if [[ "${{ matrix.db }}" == "postgres" ]]; then export MIGRATIONS_RUN=true; fi
          npm run test:e2e -- --runInBand
      - name: Show logs on failure
        if: failure()
        run: |
          echo "Tests failed. Listing backend dist tree (depth 2):";
          find backend/dist -maxdepth 2 -type f -print 2>/dev/null | head -50 || true