name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test:
    name: Test (SQLite & Postgres)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db: [sqlite, postgres]
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aquafarm
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" \
          --health-interval 5s \
          --health-timeout 5s \
          --health-retries 5
    env:
      NODE_ENV: test
      SERVICE_NAME: aquafarm-backend
      DB_TYPE: ${{ matrix.db }}
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/aquafarm
      JWT_SECRET: testsecret
      DEFAULT_TENANT_ID: default-tenant
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package.json
      - name: Install deps
        working-directory: backend
        run: npm ci
      - name: Build
        working-directory: backend
        run: npm run build
      - name: Run E2E Tests
        working-directory: backend
        run: |
          if [ "${{ matrix.db }}" = "postgres" ]; then export MIGRATIONS_RUN=true; fi
          npm run test:e2e -- --runInBand
      - name: Show logs on failure
        if: failure()
        run: |
          echo "Tests failed. Listing workspace files for diagnostics:";
          ls -R . | head -100